---
stages:
type: canonical

- name: image_conversion
  steps:

  - name: metaextract
    batch_args:
    - name: batch_size
      value: 100
    submission_args:
    - name: cores
      value: 2
    - name: duration
      value: 06:00:00
    - name: memory
      value: 5000

  - name: metaconfig
    batch_args:
    - name: n_horizontal
      value: 7
    - name: n_vertical
      value: 7
    - name: regex
      value: null
    - name: stitch_layout
      value: horizontal
    - name: mip
      value: false
    submission_args:
    - name: cores
      value: 1
    - name: duration
      value: 06:00:00
    - name: memory
      value: 3000

  - name: imextract
    batch_args:
    - name: batch_size
      value: 100
    - name: delete
      value: false
    submission_args:
    - name: cores
      value: 1
    - name: duration
      value: 06:00:00
    - name: memory
      value: 3000

- name: image_preprocessing
  steps:

  - name: corilla
    batch_args: []
    submission_args:
    - name: cores
      value: 1
    - name: duration
      value: 06:00:00
    - name: memory
      value: 3000

- name: pyramid_creation
  steps:

  - name: illuminati
    batch_args:
    - name: align
      value: false
    - name: batch_size
      value: 100
    - name: clip
      value: true
    - name: clip_percent
      value: 99.9
    - name: clip_value
      value: null
    - name: illumcorr
      value: true
    submission_args:
    - name: cores
      value: 1
    - name: duration
      value: 06:00:00
    - name: memory
      value: 2000

- name: image_analysis
  steps:
  - name: jterator
    batch_args:
    - name: batch_size
      value: 50
    submission_args:
    - name: cores
      value: 1
    - name: duration
      value: '12:00:00'
    - name: memory
      value: 3500
